### ISSUE TITLE
Batch updates reporting contention incorrectly

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#1020]
#### Environment details

  - OS: macOS Catalina 10.15.5 Beta (19F53f)
  - Node.js version: 13.7.0
  - npm version: 6.13.6
  - `@google-cloud/firestore` version: 3.7.4

#### Steps to reproduce

  1. I am using the `batchUpdates` module that I created described in #903.
  2. Since it is a dictionary of document ids, you can safely assume that no document appears more than once in the dictionary
  3. I am committing the batch updates using the `Promise.all` statement described in #903 
  4. I receive the following error regarding contention
```
Error: 10 ABORTED: Too much contention on these documents. Please try again.
    at Object.callErrorFromStatus (/api/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/src/client.ts:324:36)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/src/client-interceptors.ts:439:34)
    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/src/client-interceptors.ts:402:48)
    at Http2CallStream.outputStatus (/api/node_modules/@grpc/grpc-js/src/call-stream.ts:228:22)
    at Http2CallStream.maybeOutputStatus (/api/node_modules/@grpc/grpc-js/src/call-stream.ts:278:14)
    at Http2CallStream.endCall (/api/node_modules/@grpc/grpc-js/src/call-stream.ts:262:12)
    at Http2CallStream.handleTrailers (/api/node_modules/@grpc/grpc-js/src/call-stream.ts:398:10)
    at ClientHttp2Stream.emit (events.js:315:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:485:12)
    at emit (internal/http2/core.js:289:8)
    at processTicksAndRejections (internal/process/task_queues.js:87:22) {
```

I wouldn't expect to see that given that no document should be getting updated/modified more than once in the batch updates.

**Comment by schmidt-sebastian** [comment]
@jakeleventhal Thanks for filing this. 

We are currently emitting these errors outside of transaction if:
- there is a separate active transaction that locks one of the documents you are writing to
- if there is contention on one of the indices that needs to be updated. This can either be the key index for a single collection (as every single insert of a document writes an index entry for the document key) or an index on a field value. 

If you are hitting limits for field-value based indices, you might be able to turn them off: https://stackoverflow.com/questions/51300882/how-to-delete-single-field-indexes-that-generated-automatically-by-firestore

We need to improve the error messages here. Since we already have backend work slated for this (b/152055010), there is likely not much ore we can do. Thanks again for filing this,

**Comment by schmidt-sebastian** [comment]
@jakeleventhal Can you send me your project ID to mrschmidt(at)google.com? Our backend team wants to take a closer look.

**Comment by jakeleventhal** [comment]
Sent

**Comment by wyeo** [comment]
Hello @schmidt-sebastian 
Same issue here but with `runTransaction`

**Comment by schmidt-sebastian** [comment]
Contention is a normal condition if you are updating or reading the same documents in multiple concurrent transaction. Please limit the number of concurrent transactions that are accessing the same documents. We resolve occasional contention with retries, but since the number of retries is limited, you may have to reduce the number of transactions that are active at any given time.

**Comment by maxmoros** [comment]
I am having the same issue but only running three runTransaction(), not even concurrently (~2sec between calls). Two passed and third failed.

**Comment by schmidt-sebastian** [comment]
If you see contention in transactions that cannot be explained by concurrent usage, we can look at these if you file a customer support request that is specific to your project: https://cloud.google.com/support-hub. There is not much we can do from the SDK side.

**Comment by nifrasismail** [comment]
Is this issue is fixed ?

**Comment by schmidt-sebastian** [comment]
Please follow the advice above: If you still see contention that cannot be explained by concurrent transactions or modifications, please file a project specific issue: https://cloud.google.com/support-hub

Unfortunately, we cannot address this issues from the SDK.
