### ISSUE TITLE
FirestoreDataConverter support for Admin SDK

### ISSUE THREAD

**Issue by komape** [googleapis/nodejs-firestore#1027]
**Is your feature request related to a problem? Please describe.**
I cannot use a FirestoreDataConverter as am I used to it for the Web Client SDK. See [here on StackOverflow](https://stackoverflow.com/questions/61275909/firestoredataconverter-throws-error-for-admin-sdk-but-not-for-javascript-or-node).

**Describe the solution you'd like**
To be able to use a FirestoreDataConverter as in the Web Client SDK.

**Describe alternatives you've considered**
Manually parse the model objects, very annoying if it is possible the other way.

Already filed this in [firebase-admin-node](https://github.com/firebase/firebase-admin-node/issues/854) but I was proppsed to do it here.

**Comment by thebrianchen** [comment]
@komape Thanks for writing in! `FirestoreDataConverter` support does exist for the [Admin SDK](https://googleapis.dev/nodejs/firestore/latest/Query.html#withConverter), though at the current time, the `FirestoreDataConverter` is different between Firestore Web SDK and the Admin SDK. The link you provided is referring to the Client SDKs, where the Node.js *client* SDK does not support `FirestoreDataConverter`. 

The `FirestoreDataConverter` is supported in the admin SDK ([link](https://googleapis.dev/nodejs/firestore/latest/DocumentReference.html#withConverter)). However, the converters' `fromFirestore()` methods currently have different signatures, which makes the converters not compatible with each other. We currently have a PR (#965) in flight to standardize the Node converter to also use `QueryDocumentSnapshot` that will be released with the next major version bump. Note that you'll still have to rewrite the converter to use it in the Node SDK because unlike the Web SDK, the Node SDK does not have `SnapshotOptions`.

I'm going to mark this issue closed, but feel free to reply if you have any other questions!

**Comment by komape** [comment]
@thebrianchen thanks for the quick response. can you say when the next major version will be released? are talking about days, weeks or months?

**Comment by andrefedev** [comment]
Same problem here, five months have passed since then, any update?

**Comment by thebrianchen** [comment]
This was released in [v4.0.0](https://github.com/googleapis/nodejs-firestore/releases/tag/v4.0.0).
