### ISSUE TITLE
Typeguard for exists

### ISSUE THREAD

**Issue by sk-** [googleapis/nodejs-firestore#1058]
Would you consider adding an alternate way of calling `exists` in `DocumentSnapshot`s which support a Typeguard?

At the moment if you do:

```ts
const snapshot = ref.get()
if (snapshot.exists) {
  const data = snapshot.data();
  // here data can still be undefined to the TS compiler
}
```

The problem is that `exists` does not have a type guard, and in fact they are not supported in getters. See https://github.com/Microsoft/TypeScript/issues/7150.

However, if you could add a new method for `exists` you could solve the problem, with something like the following:

```ts
class DocumentSnapshopt<T> {
    private _fieldsProto: ApiMapValue | undefined;
    newExists(): this is QueryDocumentSnapshot<T> {
        return this.raw !== undefined;
    }
    data() {
        if (this._fieldsProto === undefined) {
            return undefined;
        }
        return ...
    }
}

const rawResult = new RawResult();

if (rawResult.exists()) {
    const data = rawResult.decode()
}
```

See https://stackoverflow.com/questions/61510649/typeguard-for-property/61520437#61520437 and this [TS Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=1#code/C4TwDgpgBAShDOBXANsKBeKBvAvgKDwEsA7YCAJwDMBDAY2hmoHc4lUBRAD0PmHigicyxACb9GLBCjRY8UeVBERaAeyUAKAJQAuWFNR58eWsmrxxzVtOxyFYcoQBu1MlHLNdvB8QDmUAD5QiKIQlCQQIgDctvKCPHxausAAFjxQaRJWHNy8-LIKBW4QwIjkxFApPAB07kxQAITomMFKYcQR0QX4BUqqGjp6bGiBLaHhIjaFCoSUUOqV8DXMGE1BIW0RmpNTheTFpeWjG1Exhd07eyVlFamLtVBmg9Kn+EaqxLxulvpomO11mR+WmixhUHzQIhc1AAstQQAAhCAAVXW4wwX0kQyqvTUEGBRFm6lqWWAVTiuS0W3yCgA9DSoAAJCjQSHAahQWjUYjEFRoABG0CO41O70+rPZmGJP2xylxWkMeCAA)

**Comment by schmidt-sebastian** [comment]
@sk- Thanks for filing this. We have been trying to do this for a long long time. I will play around with it to see if we can introduce this as a non-breaking change.

**Comment by schmidt-sebastian** [comment]
We discussed this internally and decided against this at this point. The only way to make this work cleanly is by changing `exists` into a method, which is a subtle breaking change that will affect a lot of users.

The proposal in #1064 also breaks users since the return type of `DocumentReference.get()` is no longer DocumentSnapshot. We could work around this by introducing a `NonExistingDocument` type, but this would increase complexity quite significantly.

We are willing to reconsider if this change can be made relatively trivially without adding API surface.
