### ISSUE TITLE
Transaction silently fails depending on the condition of the concurrent conflicting transaction.

### ISSUE THREAD

**Issue by jackdreilly** [googleapis/nodejs-firestore#1094]
#### Environment details

  - OS: macos 
  - Node.js version: 10.15.3
  - npm version: 6.14.4
  - `@google-cloud/firestore` version: 3.8.1
  - `firebase-admin` version: 8.12.1

#### Steps to reproduce

Run the code below:

```javascript

const admin = require("firebase-admin");
admin.initializeApp();
const firestore = admin.firestore();

const sleep = (s) => new Promise((resolve) => setTimeout(resolve, s * 1000));

async function main() {
  const ref = firestore.doc("a/b");
  await Promise.all([
    firestore.runTransaction(async (t) => {
      await t.get(ref);
      await sleep(2);
      t.set(ref, { a: 1 });
    }),
    firestore.runTransaction(async (t) => {
      await t.get(ref);
      await sleep(1);
      t.set(ref, { a: 2 });
    }),
  ]);
  // prints {a: 1}
  console.log((await ref.get()).data());

  await Promise.all([
    firestore.runTransaction(async (t) => {
      await t.get(ref);
      await sleep(2);
      t.set(ref, { a: 1 });
    }),
    firestore.runTransaction(async (t) => {
      //   await t.get(ref);
      await sleep(1);
      t.set(ref, { a: 2 });
    }),
  ]);
  // prints {a: 2}
  console.log((await ref.get()).data());
  process.exit(0);
}

main();

```

There are two scenarios, played out in serial above:

1. In parallel, two transactions both call `get` on `ref` before updating `ref`. The second transaction in the list always completes before the first (as it waits for 2 seconds vs. 1). In this scenario, the concurrent update is detected, and transaction 1 is retried, and succeeds on the 2nd try, resulting in the final value for `ref` of `{a: 1}`.

2. Only the first transaction calls `get` on `ref`. The second transaction only modifies `ref` without `get`ing.  In this scenario, the second transaction update successfully, as expected. Unexpectedly, the first transaction succeeds AND performs no modifications. Thus, the first transaction is never retried, and does not perform its expected update, and the final value of `ref` is `{a: 2}`.

As you can see, the only difference in code between scenario 1) and 2) is a single commented-out line.

If this is expected behavior, could you please explain why? In my mind, I would imagine that the first transaction's behavior should not be impacted by the condition in which the other transaction modifies the value that it requires, yet there is clearly two different types of behavior on the first transaction, depending on the condition of the other transaction.

For instance, if you run a long-running update transaction with the admin library, and concurrently modify the value it's locking on the web UI, then you will trigger behavior `2.` listed above, which, again, is surprising to me that the update transaction would not fail and retry.

**Comment by jackdreilly** [comment]
Additional detail: I ran an equivalent test against @firebase/firestore JS SDK, and that code exhibits only the behavior of Scenario 1) above for both Scenario 1) and Scenario 2), i.e., the JS SDK does not exhibit this issue

**Comment by schmidt-sebastian** [comment]
@jackdreilly Thank you for taking the time to write up such a detailed issue. 

The difference between this Server SDK and the @firebase/firestore Web SDK is that the Web SDK optimistically locks the documents that are read during a transaction, whereas this (and all Server SDKs) use pessimistic locks. The behavior is different because we expect the Server SDK to be used in environments where the network link is strong enough that pessimistically locked documents will only be locked for short periods of time. A pessimistic lock is removed when the transaction commits or after 60s of inactivity.

With pessimistic locking, a document is locked as soon as it is read in a scope of a transaction. If another transaction reads the same document, that transaction will fail. This explains why in your first example, it is basically luck which transaction obtains the lock and wins. The duration of the sleep (as long as it is under 60s) should have no bearing on the outcome. The outcome is only driven by the first read request that reaches the backend.

In your second example, the first transaction always wins the lock in a Server SDK, since the second transaction only accesses the document after a 1 second delay.

The optimistic transactions in the Web SDK don't actually obtain any locks. The Web/iOS/Android SDK only verify at commit time that the documents that have been read during a transaction haven't been modified. With this model, your timeouts dictate which transaction wins.

**Comment by jackdreilly** [comment]
@schmidt-sebastian Thanks for taking the time to explain the details of admin vs. client sdks for me. It definitely helps me understand the outcomes of the cases better.

Still, I have one more thing which is perplexing to me:

```js
await firestore.runTransaction(async (t) => {
    await t.get(ref);
    console.log('locked');
    await sleep(5);
    console.log('awake');
    t.set(ref, { foo: 'bar' });
});
```

If you run this snippet above, then modify `ref` on the web UI of your firestore DB after seeing `'locked'` and before `'awake'`, then the transaction is completely ignored. It is never retried, and `ref` never takes the value of `{foo: 'bar'}`.

You can increase `5` to be as large as you want, the result is the same, the transaction is ignored.

If you don't simultaneously edit `ref` on the Web UI, then the transaction applies successfully.

This behavior I don't understand. Why is the transaction never applied/retried?

**Comment by schmidt-sebastian** [comment]
@jackdreilly I am stumbled by this behavior as well. I filed Google internal bug b/157934567 as a means for us to research this. I will get back to you should when we know more.

**Comment by schmidt-sebastian** [comment]
Our backend team reproduced your issue. The reason you see this behavior is that the change from the console is blocked because of the Server SDK's lock on the document. Once the Server SDK commits the transaction, the commit from the console is applied. Hence, the end result is that the change in the console wins. 

If this happens to you in a real life application, you would have to use transactions for all writes, in which case the "console commit" would fail.

**Comment by jackdreilly** [comment]
thanks for the update. Indeed I could verify this myself by adding a
simultaneous pinging loop for the reference, which verifies that the value
remains locked at the old value and then immediately updated to the console
value after the local lock finishes.
