### ISSUE TITLE
[FR] Improve the BulkWriter API to prevent UnhandledRejections

### ISSUE THREAD

**Issue by sk-** [googleapis/nodejs-firestore#1282]
The `BulkWriter` class was made public in version 4.1.0. however, it has some use disadvantages compared to using a `BatchWriter`.

The problem lies in the fact that `close` never fails, and the fact that writing (`update`, `delete`, `set`) returns a promise.

This makes it difficult and awkward to correctly handle errors, which is absolutely necessary on cloud functions, as `UnhandledRejections` will make the whole function to fail with a very cryptic error.

It'd be great if we could write something like:

```ts
const writer = db.bulkWriter();
writer.update(ref1, {...});
writer.update(ref2, {...});
try {
  await writer.commit();
} catch (error) {
  // decide whether to continue, fail, log or do something else based on the error.
  // error could be an object having a `failures` and `succeses` fields, where each failure or success has the all the arguments of the write operation. 
  // Or something similar to the result of promiseAllSettled. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled
}
```

Note that using `WriteBatch` resembles the proposed API.

Compare that to what one needs to do today.

```ts
let sharedState = ...;
const writer = db.bulkWriter();
 // depending on whether we want to skip failures or actually fail what the catch function will be
writer.update(ref1, {...}).catch(...);
writer.update(ref2, {...}).catch(...);
await writer.close();
// Check shared state
```

**Comment by thebrianchen** [comment]
@sk- Thanks for the feedback! When designing the BulkWriter API, we considered but ultimately decided against such a design due to the additional state management that would be required to map the index-based results array back to the original requests. In addition, `BulkWriter` does not have the 500-write limit that `WriteBatch` has and automatically batches and sends writes. This would make defining the return behavior for `flush()` more complex when `flush()` is called several times in succession with writes in between (returning all writes vs. just the writes in between `flush()` calls).

However, you bring up a good point that having floating promises can result in hard to debug `UnhandledPromiseRejection` errors. From here, we are looking at two options:
1. Expose an error handler that BulkWriter will run when an operation fails.
2. On `close()`, return a list of document writes that succeeded, and a list of document writes that failed. 

In both cases, we would be adding a `catch()` handler that would prevent the `UnhandledPromiseRejection` errors from being thrown.

Would either of these options help your use case? Are you hoping to blindly retry writes that failed, or run some other logic?

**Comment by sk-** [comment]
Thanks @thebrianchen for the reply.

In our case we just want to log those requests that failed, as those will certainly indicate some error or data corruption in our side. Think of failed updates or deletes. We also want to stop execution of subsequent code.

In our use case I don't think we are going to be calling `flush` repeatedly, as we are mostly replacing `WriteBatch` with `BulkWriter`.

Of the two options I think the second one works better with async/await and would be similar to what I proposed. Defining a default error handler may avoid repetition (if the writes are not done in a loop) but still requires to handle a shared state, that you need to check after closing the writer.

Compare:
```ts
let sharedState = ...;
const writer = db.bulkWriter();
 // depending on whether we want to skip failures or actually fail what the catch function will be
for(const id of usersToUpdate) {
  writer.update(db.collection('users').doc(id), {...}).catch((error) => {...});
}
await writer.close();
// Check shared state
```
vs
```ts
let sharedState = ...;
const writer = db.bulkWriter({errorHandler: (error) => {...}});
 // depending on whether we want to skip failures or actually fail what the catch function will be
for(const id of usersToUpdate) {
  writer.update(db.collection('users').doc(id), {...});
}
await writer.close();
// Check shared state
```

**Comment by thebrianchen** [comment]
Just a quick update that this feature is still being considered and worked on, but I've had several other issues come up in the meantime. I'll be getting to working on this soon!
