### ISSUE TITLE
Converter toFirestore not work on update

### ISSUE THREAD

**Issue by neko1216** [googleapis/nodejs-firestore#1309]
I notice that the toFirestore converter only works on set and create method in the write batch, but not the update method.
When I update the document with a object instance of for example an A class, it always throws error:

> Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "dataOrField" is not a valid Firestore document. Couldn't serialize object of type "A". Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).

Is there any reason that the update method can't work with the converter?

**Comment by thebrianchen** [comment]
@neko1216 Thanks for writing in! `set()` and `create()` take in objects of type `T` or `Partial<T>` ([signatures](https://googleapis.dev/nodejs/firestore/latest/DocumentReference.html#set)). However, `update()` takes in an alternating list of field/value pairs that are untyped and may or may not exist on an object of type `T`. Since the `toFirestore()` method converts objects of type `T` to Firestore's `DocumentData` type, the converter would not be compatible with `update()`'s `UpdateData` type.
