### ISSUE TITLE
Proposal: move all the samples on same repository

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/nodejs-firestore#1358]
Currently in All other NodeJS library sample's are on same repository while in firestore samples are located on [snippets-node](https://github.com/firebase/snippets-node) repository.

Can we move all the samples in this repository?

cc @googleapis/yoshi-nodejs @googleapis/api-firestore

**Comment by crwilcox** [comment]
We could move these theoretically, though we would need to make sure to coordinate with firebase. cc: @samtstern

**Comment by schmidt-sebastian** [comment]
@samtstern - Do you have thoughts on this?

I would like to either close this issue or come up with a plan to address it.

**Comment by JustinBeckwith** [comment]
One thing I like about having the samples together with the source - they make for _great_ integration tests.

**Comment by samtstern** [comment]
I have no strong feelings but I will say this issue is phrased in a Cloud-centric way.  It's worth pointing out that from a Firebase perspective all our snippets are in one place now and moving the Firestore ones here would make things more spread out, not less.

If someone else wants to do the work of moving them and updating the docs I'd approve the PRs, fine either way.

**Comment by schmidt-sebastian** [comment]
Going to close this since it does not look like it will happen anytime soon :)
