### ISSUE TITLE
BulkWriter auto flushes once _maxBatchSize is exceeded, even without .close()

### ISSUE THREAD

**Issue by cvharris** [googleapis/nodejs-firestore#1399]
#### Environment details

  - OS: Mac OSX Catalina
  - Node.js version: 14.15.3
  - npm version: 6.14.9
  - `@google-cloud/firestore` version: 4.8.0
 
The `_maxBatchSize` of BulkWriter is 20, and it seems that when more than 20 operations are added to a BulkWriter they auto-flush and commit the changes at some point, even when the script does not explicitly call `.close()` or `.flush()`. This is problematic because errors could be thrown in between operations being added and the commits will still take place.

#### Steps to reproduce

  1. In a node firebase function, create an instance of BulkWriter `const bulk = admin.firestore().bulkWriter()`
  2. Add 20 various operations to the BulkWriter (set, create, update, delete)
  3. Never call `.close()` or `.flush()` and let script finish. No operations are committed.
  4. Update script with a 21st operation and rerun it without calling `.close()` or `.flush()`
  5. The first 20 operations will have committed, but the 21st will not have

It seems that there should be a clear intention to commit before allowing these to be auto-flushed, especially if a script were to error, timeout, or the logic intended to not commit for some reason. The desirable behavior would be instead to go along adding operations to the BulkWriter and, if `.close()` never gets called in the script, the operation promises are never committed.

**Comment by thebrianchen** [comment]
@cvharris Thanks for writing in!

The `flush()` and `close()` methods are intended for developers to wait for writes to complete. Though `flush()` and `close()` send existing batches, BulkWriter purposely allows writes to be automatically sent on their own. The design of BulkWriter prioritizes automatically sending writes as they are enqueued, similar to other streaming APIs. Firestore automatically sends writes in batches of 20 to optimize throughput in the underlying backend API (which explains why the first 20 writes are buffered), but the intention is to batch and send writes as soon as they are made.

If you want to batch writes manually and send them conditionally based on the success or failure of other writes, I recommend you use the WriteBatch API. Since this is WAI, I'm going to mark this feature as closed, but please feel free to ask any other questions you may have!
