### ISSUE TITLE
16 UNAUTHENTICATED in nodejs server

### ISSUE THREAD

**Issue by andrelmlins** [googleapis/nodejs-firestore#1420]
I get the following error at random in my nodejs server It doesn't happen when in my local environment. 

16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

#### Environment details

  - OS: Linux
  - Node.js version: 12.x
  - `@google-cloud/firestore` version: ^4.9.2

#### Code

```ts
class FirestoreService {
  private static firestore: Firestore;

  constructor() {
    if (!FirestoreService.firestore) {
      FirestoreService.firestore = new Firestore({
        projectId: process.env.FIREBASE_PROJECT_ID,
        credentials: { client_email: process.env.FIREBASE_CLIENT_EMAIL, private_key: process.env.FIREBASE_PRIVATE_KEY },
        ssl: true,
        maxIdleChannels: 2,
      });
    }
  }
}
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by schmidt-sebastian** [comment]
Are you able to use `keyFilename` and directly point to a the service-account.json file you downloaded from the Console? See https://github.com/googleapis/nodejs-firestore/blob/ab057f7b362a2929ebffa19e570d3e9cd23bc964/types/firestore.d.ts#L130

What you have should work, but it does have a higher likelihood of introducing misconfigurations and unfortunately, we cannot debug them here since we would need access to your credentials.

If `keyFilename` does not solve your issue, please file a support request. We can then take a look at the permissions associated with your service account: https://cloud.google.com/support-hub
