### ISSUE TITLE
Firestore extensions

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-firestore#1519]
As [requested](https://github.com/googleapis/nodejs-firestore/issues/1457#issuecomment-810322888) by @wu-hui, I'd like to share with you the extensions package my team has been working on, which we finally managed to open source today.

https://github.com/ridedott/firestore-extensions

Probably the most complex feature that we implemented there were resumable subscriptions, which we use in combination with Cloud Run to avoid background processing (we have gRPC streams from clients and we pause a subscription when all streams are closed). We are not sure if the implementation is correct and optimal, however our tests on some internal services yielded positive results:
- 90% lower memory usage.
- Much lower CPU utilization.
- Significant reduction in Firestore document reads (depending on traffic).

If you'd like to look into the implementation and potentially provide me with some feedback, that would be awesome :slightly_smiling_face: The code is [here](https://github.com/ridedott/firestore-extensions/blob/master/src/subscriptions/collections.ts).

Next to this feature, some utilities we developed:
- [Firestore ID to UUID converter](https://github.com/ridedott/firestore-extensions#firestore-id-to-uuid-converter), useful when internal IDs are Firestore IDs, but external APIs/standards require UUIDs.
- A [version of `getAll`](https://github.com/ridedott/firestore-extensions/blob/a5353a2397795b9547ac6f6bda57ad9507ff21a6/src/batch/index.ts#L179-L203) with more strict typings (document types based on reference types).

**Comment by samtstern** [comment]
@merlinnot this is really cool! I'd love to feature it on one or both of these sites:

- https://firebaseopensource.com
- https://devlibrary.withgoogle.com

I'm a maintainer on both so if you follow the instructions on the homepage(s) I'll approve your submission and get it listed. I think other Firebase developers will love this.

I'm going to close this issue because there's no actual "Issue" here with the `nodejs-firestore` library but we can definitely continue the discussion!

**Comment by merlinnot** [comment]
Submitted to both!
