### ISSUE TITLE
`ignoreUndefinedProperties` doesn't work on doc.update

### ISSUE THREAD

**Issue by advaith1** [googleapis/nodejs-firestore#1580]
I noticed that doc.update was clearing a property sent as `undefined` although `ignoreUndefinedProperties` was set. I searched and found #1392, so I updated firebase-admin and found that while doc.set(..., { merge: true }) worked properly, doc.update(...) still did not. I changed the code to use .set for now (set with merge seems to act the same as update if the document already exists, but I assume .update is recommend if the doc definitely already exists.)

#### Environment details

  - OS: Windows 11 20H2 22000.100
  - Node.js version: v14.15.1
  - npm version: v6.14.11, but I use pnpm v6.9.1
  - `@google-cloud/firestore` version: firebase-admin v9.11.0

#### Steps to reproduce

  1. Have a document with a field present
  2. Use doc.update and provide an object with that field set to `undefined`

in the following examples, the issue can be seen when `option('content')` is a present string and `option('ephemeral')` is undefined

Has issue (`ephemeral` gets cleared):
```js
        if (option('content') || option('ephemeral') !== undefined)
            await db.collection('guilds').doc(interaction.guild_id).update({
                [command.id]: {
                    content: option('content'),
                    ephemeral: option('ephemeral')
                }
            })
```

Works (`ephemeral` is not modified):
```js
        if (option('content') || option('ephemeral') !== undefined)
            await db.collection('guilds').doc(interaction.guild_id).set({
                [command.id]: {
                    content: option('content'),
                    ephemeral: option('ephemeral')
                }
            }, { merge: true })
```

**Comment by thebrianchen** [comment]
@advaith1 Thanks for reporting this issue and providing easy repro steps! I was able to reproduce this as well, and I'll try to get a fix out soon.

**Comment by thebrianchen** [comment]
@advaith1 This is actually WAI. When you call `set()` with `{merge: true}`, Firestore only replaces the values specified in the data argument. Fields omitted from the `set()` call remain untouched, which is why `ephemeral` is not modified.

However, when you call `update()`, Firestore updates field with what is provided in the data argument. In your case, the `id` field is updated with the provided data that doesn't include `ephemeral: undefined`, which is why the field gets cleared. I'm going to close this issue, but feel free to ask any other questions you may have!
