### ISSUE TITLE
bundle size is > 5MB

### ISSUE THREAD

**Issue by dschroe93** [googleapis/nodejs-firestore#1617]
Hey guys,

I am using the following es-import in my cloud function:

```
import {Firestore} from '@google-cloud/firestore';
// business logic ...
```

As soon as I am bundling this code with esbuild, it produces a bundle size of around 5MB (the same size as this lib has).
When removing the lib the bundle size goes down to single-digit KBs.

Do you know why this is? Do you use incorrect/full imports in your lib?
Tree-shaking in my case is not really possible as I am transpiling to commonjs.

Any help is appreciated.

**Comment by JasonHoku** [comment]
I think you are using the wrong firestore library?

By cloud function do you mean a firebase functions type function?

Because the [documentation](https://firebase.google.com/docs/functions/get-started), along with my understanding, advises to use the following to access the Firebase Firestore api through Firebase Functions:
`const admin = require("firebase-admin");`
`var db = admin.firestore();`

**Comment by JasonHoku** [comment]
I use firebase fairly extensively, I generally use CRA with webpack for my front end, but on my backend functions I deploy using the firebase functions emulator and firebase-tools cli:

My functions are not bundled or minified though, I've never ran into wanting/needing that.

Some Functions examples from my work:

Discord Community Announcer Firebase Functions Bot:
https://github.com/JasonHoku/HokuBot/tree/main/functions

Payment Processing Backend Functions:
https://github.com/JasonHoku/MicroHawaii/tree/main/functions

Hope it helps, best of luck!

**Comment by schmidt-sebastian** [comment]
We do not really look at the size of this library, as most of our users do not use bundles. In fact, we have some dependencies that we lazy-load in order to speed up certain code flows. Bundling breaks this and includes all code, no matter whether it is used or not.

If you want to use a more lightweight http client, you should try Firestore Light and see if you can make it work with your server setup. Be warned though: It is meant as a client library, which means that you will not be able to use service account based authentication.

https://firebase.google.com/docs/firestore/solutions/firestore-lite

**Comment by paul-uz** [comment]
interestingly, in 2025, using this package over the firebase-admin one, with bundling, saves me about 1mb in filesize
