### ISSUE TITLE
FirestoreDataConverter type def is different from Reference

### ISSUE THREAD

**Issue by pelly-ryu** [googleapis/nodejs-firestore#1833]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
Defining converters for both front and back.
- What code you've already tried: no
- Any error messages you're getting: no

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

In the reference( https://firebase.google.com/docs/reference/node/firebase.firestore.FirestoreDataConverter#fromfirestore ):
`fromFirestore` has the 2nd param: `options: SnapshotOptions`
but I can't find it in the definition of `FirestoreDataConverter<T>` interface.

It is (6.5.0)
```
fromFirestore(snapshot: QueryDocumentSnapshot): T;
```

Which one should be fixed? or I'm reading a wrong part?

**Comment by dconeybe** [comment]
Hi @pelly-ryu. Something indeed appears to be incorrect with that documentation. Thank you for reporting. I'm looking into it.

**Comment by dconeybe** [comment]
Ok so it turns out that you were looking at the wrong documentation. The correct documentation is here: https://cloud.google.com/nodejs/docs/reference/firestore/latest (linked to from https://github.com/googleapis/nodejs-firestore/blob/main/README.md).

The documentation you were looking at was confusingly labeled "Node.js (Client)" which is a _client_ SDK. This GitHub repository is a _server_ SDK.

The confusion is understandable! Hope this helps.
