### ISSUE TITLE
Firestore Server Timestamps via the REST API

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-firestore#203]
[copying customer's request from the email]

How can server timestamps be adopted through the Firestore REST API, like in a
PATCH request?

https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases.documents/patch

Server timestamps can easily be adopted through the JS API, like

```js
firebase.firestore.FieldValue.serverTimestamp()
```

but they remain, confusingly, undocumented in the REST API.

I tried every permutation I could think of after examining the network requests
made by various frontends, like the API Explorer), but all were rejected. E.g.

```js
    fieldTransforms: {
        "fieldPath": "test",
        "setToServerValue": "REQUEST_TIME"
    }
```

How can a server timestamp be adopted via the Firestore REST API?

**Comment by schmidt-sebastian** [comment]
Server Timestamps cannot be set via the normal document CRUD operations, since they are implemented as a `DocumentTransform`. To use Server Timestamps, you have to use one of the Rest API that accepts a the `Write` type. A `Write` can either be a document CRUD operation or a `DocumentTransform`.

An example request that sets a server time to a single field would look like:

```
POST https://firestore.googleapis.com/v1beta1/projects/foo/databases/(default)/documents:commit?key={YOUR_API_KEY}

{
 "writes": [
  {
   "transform": {
    "fieldTransforms": [
     {
      "fieldPath": "foo",
      "setToServerValue": "REQUEST_TIME"
     }
    ],
    "document": "projects/foo/databases/(default)/documents/foo/a"
   }
  }
 ]
}
```

**Comment by alexander-fenster** [comment]
Thanks! The customer confirmed the solution worked.
