### ISSUE TITLE
Is it possible to have listCollections with option to list only missing documents?

### ISSUE THREAD

**Issue by Thaina** [googleapis/nodejs-firestore#423]
Suppose there is 100000 documents in collection and there was 10 missing documents with subcollection we need to handle, it would be more practical to list only those 10 docs instead of going through all 100000 docs for just 10

So if it possible please expose some API to handle this scenario

**Comment by schmidt-sebastian** [comment]
Hi! This is currently not supported by our backends. We hope that we can alleviate some of your concerns with improvements that we are planning for our Query API, but since most of the development here is in the early stages, I don't have much to share at this point.

Sorry that I don't have better news for you.
