### ISSUE TITLE
Documentation Request for firestore.collection.doc.delete

### ISSUE THREAD

**Issue by vajahath** [googleapis/nodejs-firestore#599]
Please provide a short note/sample about the `precondition` argument the `delete()` function can accept in the doc page.
I was referring [firestore delete docs](https://firebase.google.com/docs/firestore/manage-data/delete-data) and couldn't found any.
It would be nice if you reflect the docs on the [definition file](https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L349) also (for better IDE support).

Relevant code:
I was using firestore via [firebase-admin](https://github.com/firebase/firebase-admin-node):
```ts
  await fireAdmin
    .firestore()
    .collection("projects")
    .doc("doc-id")
    .delete(/* precondition */);
```
![image](https://user-images.githubusercontent.com/12165822/56087843-f8900380-5e90-11e9-9dff-162df862c768.png)

**Comment by schmidt-sebastian** [comment]
Hi! Thanks for reporting this issue. The `.d.ts` file should allow your IDE to autocomplete all possible Preconditions. In the meantime, I will modify the sample for https://cloud.google.com/nodejs/docs/reference/firestore/1.1.x/DocumentReference#delete to include the use of a Preondition.

By the way, it's unlikely that we will include this feature in our shared API documentation (the " firestore delete docs" you linked to) since Preconditions are only available via the Server SDKs.

**Comment by lautarovc** [comment]
Hi! The docs and examples are also missing the exists precondition, that determines if a document should exist before deleting. This is defined in the [document.ts](https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/document.ts#L1012) file, Precondition class.
