### ISSUE TITLE
Add feature to allow collections to auto increment document id when inserting new documents.

### ISSUE THREAD

**Issue by Rotorsoft** [googleapis/nodejs-firestore#710]
It would be very useful to have auto increment functionality in collections where the document id is a padded string of integers. Collection refs could also have metadata with the last document id automatically populated without having to query by __name__ desc limit 1. This feature would greatly simplify the creation of event streaming (event sourcing) applications.

**Comment by schmidt-sebastian** [comment]
@Rotorsoft Thanks for this suggestion. While we support adding documents based on randomly generated Document IDs, we do not support auto-incrementing IDs. This is due a limitation on our backend: Since document IDs are indexed, using monotonically increasing IDs causes Index hotspotting. This hotspotting reduces the write throughput for the affected collection.

You can find some more information here: 
- https://cloud.google.com/firestore/docs/best-practices#document_ids
- https://cloud.google.com/firestore/docs/best-practices#hotspots

**Comment by Rotorsoft** [comment]
Hi Sebastian. Thanks for the quick reply! 
Is there any other google storage service that supports this kind of functionality efficiently and can be easily integrated into a Firebase project (mainly Firebase Authentication and Functions). I see a lot of value in having a simple event log storage service in your ecosystem. Many projects are transitioning to a DDD, Event Sourcing, CQRS paradigm and a Serverless platform like Firebase would benefit from supporting these patterns.

**Comment by schmidt-sebastian** [comment]
The RTDB supports incrementing keys, but they might not fit your use case since they are [not integer keys]( https://firebase.google.com/docs/reference/admin/node/admin.database.Reference.html#push) - but we don't have a way to populate a `next` pointer without invoking a Cloud Function.

For what it is worth, you might be able to use Firestore if you able to set one of your document fields to a [ServerTimestamp](https://googleapis.dev/nodejs/firestore/latest/FieldValue.html#.serverTimestamp). You could then generate an ordered list by issuing a Query with this constraint.
Note, however, that high frequency writes to this field will expose you to the same Index hotspotting problem.

**Comment by Rotorsoft** [comment]
Yep, I'm already doing that but with a number field instead. I have a public npm module at @rotorsoft/event-store where firestore was my first attempt to solve this in a serverless platform. I've been planning a CosmosDb and/or DynamoDb port, but they also have limitations... seems like CosmosDb might be the best compromise out there. I love the simplicity of Firebase though, and for my current use cases the hotspotting issue doesn't seem like a show stopper. I also found that AWS is working on a blockchain solution and the QLDB service is probably a step in the right direction but not sure yet about the pricing and API. Do you know if Google is working on something similar? I guess I'll have to work around the current limitations, but still hoping the immutable ledger paradigm will make it to the serverless cloud sooner than later. Thanks!

**Comment by schmidt-sebastian** [comment]
Unfortunately, I can't tell you about products not listed here: https://cloud.google.com/products/
