### ISSUE TITLE
Writing zero-length Buffer fails at GRPC

### ISSUE THREAD

**Issue by 5argon** [googleapis/nodejs-firestore#763]
Buffer is accepted as one of Firestore submitted field and would becomes `Blob`. For example this works when placed in a pure JS object to be set to Firestore document. : `Buffer.alloc(1)` Which it shows up as `AA==` in the Firestore console.

However when using `Buffer.alloc(0)` to create a zero-length buffer as described in https://nodejs.org/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding this error is thrown on trying to set that value to Firestore : 

```
     Error: Cannot convert firestore.v1.Value with type unset.
      at Http2CallStream.call.on (node_modules/@grpc/grpc-js/build/src/client.js:96:45)
```

**Comment by schmidt-sebastian** [comment]
@thebrianchen Can you take a look at this?

**Comment by thebrianchen** [comment]
@5argon  This seems to be an issue with our dependency on ProtobufJS ([issue](https://github.com/protobufjs/protobuf.js/issues/1218)). Using `Buffer.alloc(0)` creates an empty buffer that is not written to the message in ProtobufJS, so our backend throws the error you're getting. 

Since this is not something we can fix in our client, please follow the issue along that thread. Once it's resolved, we will update our dependencies to include new version. Sorry there's nothing else we can do at this time!
