### ISSUE TITLE
Connect to firestore in a different project

### ISSUE THREAD

**Issue by francesco-clementi-bip** [googleapis/nodejs-firestore#804]
I have actually a google app engine in "project-1", but the firestore is in "project-2".
Is it possible to create a connection with firestore in a different project then the one of nodejs server?

**Comment by bcoe** [comment]
@francesco-clementi-bip you should be able to facilitate this by initializing firestore with a service account, from "project-2", rather than relying on default credentials loaded in app engine.

You do so by creating a service account with access to firestore, in the IAM UI, and then pointing to this JSON file with the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.

see: https://cloud.google.com/docs/authentication/getting-started

Let me know if this does the trick for you :+1:

**Comment by schmidt-sebastian** [comment]
Please let us know if you have any issues with the instructions linked to above.
