### ISSUE TITLE
Firestore includes two copies of grpc in node_modules which are both very large

### ISSUE THREAD

**Issue by lewchuk** [googleapis/nodejs-firestore#96]
The node_modules for a project containing only firestore as it's dependency are quite large (~150MB depending on exact OS/configuration). Most of this comes from the grpc dependency which is about 50MB and most unfortunately is included twice. Once at the top level `node_modules/grpc` and once within the node_modules for firestore `./node_modules/@google-cloud/firestore/node_modules/grpc`.

Is there any way to only include grpc once when installed? Having this massive dependency makes deploying packages with firestore difficult where the size of the deployment package is constrained.

#### Environment details

  - OS: mac osx and linux (node 6.10.3 docker image)
  - Node.js version: 6.10
  - npm version: npm 3.10.10 and yarn 1.3.2
  - @google-cloud/firestore version: 0.10.0 and 0.10.1

#### Steps to reproduce

  1. Create a package.json file with a single dependency: `"@google-cloud/firestore": "^0.10.1"`
  2. Run `yarn install --production` or `npm install --production`
  3. run `find . -name grpc` and note the two copies of grpc.

**Comment by schmidt-sebastian** [comment]
Thank you for reporting this. We will look at removing one of these dependencies.

**Comment by schmidt-sebastian** [comment]
Note that this is due to the recent change we made to address GRPC connection issues. The work-around pegged our local GRPC version to 1.7.1. The latest 1.7.x GRPC version is however 1.7.3 - so you will see both included.

We have already the strict dependency on 1.7.1 in `master`, but have yet to release it (https://github.com/googleapis/nodejs-firestore/pull/92). I will prepare a release for this by the end of the week.

**Comment by lewchuk** [comment]
@schmidt-sebastian excellent news! I look forward to that release.

**Comment by schmidt-sebastian** [comment]
v0.11.0 was just released and should be on NPM momentarily.
