### ISSUE TITLE
Misleading error when using empty array with arrayUnion

### ISSUE THREAD

**Issue by 5argon** [googleapis/nodejs-firestore#999]
"firebase-admin": "^8.10.0"

#### Steps to reproduce

In a transaction, if using `firestore.FieldValue.arrayUnion(__)` but with argument as empty array (`[]`), the following error is shown
```
     Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
```

It is misleading as it sounds like I violated array in array restriction in Firestore. But it is not the case. An expected outcome is that it union with empty, resulting in a no-op.

**Comment by schmidt-sebastian** [comment]
@5argon Thanks for reporting this. We will get this fixed shortly.

**Comment by thebrianchen** [comment]
`arrayUnion()` takes in multiple elements to union into the array, so passing in any array value as a parameter would result in a nested array, which isn't allowed. Similarly, passing an empty array into `FieldValue.arrayUnion()` will throw an error. 

This PR throws a more detailed error message before the request is made so that the SDK no longer surfaces the more confusing backend error you are seeing.
